<a href="https://colab.research.google.com/github/amarnath235274856-cmyk/python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy


In [ ]:
import numpy as np


In [ ]:
np.arange(1,11)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.eye(5,dtype=int)


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
np.zeros((8,8),dtype="int")


array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones((4,6),dtype="int")

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [ ]:
np.full((3,8),2,dtype="int")

array([[2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2]])

In [ ]:
x=[1,2,3,4,5,6,7,8,9,10]
print(x)
np.diag(x)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


array([[ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  4,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  7,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  8,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  9,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 10]])

In [ ]:
x=np.arange(1,21)
print(x)




[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
n=x.reshape(4,5)
print(n)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
n1=x.reshape(1,4,5)
print(n1)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]]


In [ ]:
result=x.ravel()
print(result)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
result=x.flatten()
print(result)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
# numpy indexing
a=np.arange(1,21)
print(a)
a[2:5:]


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([3, 4, 5])

In [ ]:
# let check forsame 2 dimensions
b=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print(b)
print(b[0:2,1])
print(b[0::2,1])
print(b[1,1:3])



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 5]
[2 8]
[5 6]


In [ ]:
# lets check for three dimensions
c=([[[1,2,3],
     [4,5,6]],
    [[7,8,9],
     [10,11,12]]])
print(type(c))
print(c[0][0][1])
print(c[0][1][2])



<class 'list'>
2
6


In [ ]:
#slicing
import numpy as np
d=np.array([1,2,3,4,5,6,7,8,9,10])
print(d)
print(d[4])


[ 1  2  3  4  5  6  7  8  9 10]
5


In [ ]:
d[1]

np.int64(2)

In [ ]:
# for 1d
d1=([1,2,3,],[4,5,6],[7,8,9])
print(d1)

([1, 2, 3], [4, 5, 6], [7, 8, 9])


In [ ]:
print(d1[0])

[1, 2, 3]


In [ ]:
print(d1[2])

[7, 8, 9]


In [ ]:
# for 2d
d2=([[1,2,3],
     [4,5,6],
     [7,8,9]])
print(d2)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:
print(d2[2][2])

9


In [ ]:
d3=([[[1,2,3],
      [4,5,6]],
     [[7,8,9],
      [10,11,12]]])
print(type(d3))


<class 'list'>


In [ ]:
print(d3[0][1][0])

4


In [ ]:
print(d3[1][1][0])

10


In [ ]:
d4=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print(d4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(d4[0,0:3])

[1 2 3]


In [ ]:
print(d4[2,0:3])


[7 8 9]


In [ ]:
print(d4[0:3,2])

[3 6 9]


In [ ]:
d4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(d4[1:3,0:2])

[[4 5]
 [7 8]]


In [ ]:
print(d4[1:3,])

[[4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np
list=np.array([1,2,3,4,5,6,7,8,9,10])
print(list)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
print("mean of list:",np.mean(list))


mean of list: 5.5


In [ ]:
print("median of list:",np.median(list))

median of list: 5.5


In [ ]:
print("std of list:",np.std(list))

std of list: 2.8722813232690143


In [ ]:
print("max of list:",np.max(list))

max of list: 10


In [ ]:
print("sqrt of list:",np.sqrt(list))

sqrt of list: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


In [ ]:
print("sumof list:",np.sum(list))

sumof list: 55


In [ ]:
print("remove of list:",np.exp(list))

remove of list: [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]


In [ ]:
print("tan 30 value is :",np.tan(30))

tan 30 value is : -6.405331196646276


In [ ]:
list

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.sin(30)

np.float64(-0.9880316240928618)

In [ ]:
np.log(5)

np.float64(1.6094379124341003)

In [ ]:
np.tan(360)

np.float64(-3.380140413960958)

In [ ]:
np.sum(list)


np.int64(55)

In [ ]:
np.sum(list,axis=0)

np.int64(55)

In [ ]:
list_1=([[1,2,3],[4,5,6],[7,8,9]])
np.sum(list_1,axis=0)

array([12, 15, 18])

In [ ]:
np.sum(list_1,axis=1)

array([ 6, 15, 24])

In [ ]:
# insert and delete
x=[1,2,3,4,5,6,7,8,9,10]
y=[1,2,3,4,5,6,7,8,9,10]
print(x)
print(y)



[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
np.insert(x,0,[1,2,3,4,5,6,7,8,9,10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10])

In [ ]:
np.insert(x,2,y)

array([ 1,  2,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  3,  4,  5,  6,  7,
        8,  9, 10])

In [ ]:
np.delete(y,6)

array([ 1,  2,  3,  4,  5,  6,  8,  9, 10])

In [ ]:
list


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
result=np.array(a1<5)
print(result)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [ ]:
dir(list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'count',
 'index']

In [ ]:
dir(set)

['__and__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iand__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__isub__',
 '__iter__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__rand__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__ror__',
 '__rsub__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__xor__',
 'add',
 'clear',
 'copy',
 'difference',
 'difference_update',
 'discard',
 'intersection',
 'intersection_update',
 'isdisjoint',
 'issubset',
 'issuperset',
 'pop',
 'remove',
 'symmetric_difference',
 'symmetric_difference_update',
 'union',
 'update']

In [ ]:
dir(tuple)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'count',
 'index']

In [ ]:
import keyword
print(keyword.kwlist)
print(len(keyword.kwlist))


['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']
35


In [ ]:
import numpy as np
s1=np.array([[1,2,3],[4,5,6]])
print(s1.T)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
np.transpose(s1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
x=np.array([[1,2,3,4,5,6]])
print(x)

[[1 2 3 4 5 6]]


In [ ]:
y=np.array([[1,2,3,4,5,6]])
print(y)

[[1 2 3 4 5 6]]


In [ ]:
np.hstack((x,y))

array([[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]])

In [ ]:
np.vstack((x,y))

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [ ]:
a=np.array([0,1,2,3,4,5,6,7,8,9,10])
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
b=a.copy()
b[5]=143
print(b)

[  0   1   2   3   4 143   6   7   8   9  10]


In [ ]:
a   #a does not change

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
b      #b does change  in copy

array([  0,   1,   2,   3,   4, 143,   6,   7,   8,   9,  10])

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
b=a.view()
b[2]=200
print(b)

[  1   2 200   4   5   6   7   8   9  10]


In [ ]:
a          #a changes


array([  1,   2, 200,   4,   5,   6,   7,   8,   9,  10])

In [ ]:
b          # b changes in view

array([  1,   2, 200,   4,   5,   6,   7,   8,   9,  10])

In [ ]:
# difference between ravel and flatten
import numpy as np
result=np.array([[1,2,3],[4,5,6],[7,8,9]])
result

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
x=result.flatten()                    #flatten
print(x)

[1 2 3 4 5 6 7 8 9]


In [ ]:
y=result.ravel()
print(y)

[1 2 3 4 5 6 7 8 9]


In [ ]:
print(np.shares_memory(x,result))    #   ravel means view

False


In [ ]:
print(np.shares_memory(y,result))      # flatten means copy


True
